const BAM_CATEGORIES = [
    // ==========================================
    // 1. BAHARATLAR, SOSLAR & TÜRK KAHVESİ (52)
    // ==========================================
    {
        id: "baharat",
        icon: "fa-mortar-pestle",
        title: "Baharatlar, Soslar & Türk Kahvesi",
        shortDesc: "Özel karışımlar, klasik baharatlar, tuz çeşitleri, öğütücüler, sirkeler, salçalar, atom biberi ve taze çekim Türk kahvesi. 52 çeşit.",
        color: "#E65100",
        products: [
            { name: "B&M Mangal Baharı (İmza)", price: "550", unit: "TL/kg" },
            { name: "Urla Et Baharı (Kırmızı Et)", price: "650", unit: "TL/kg" },
            { name: "Ege Balık Baharı", price: "590", unit: "TL/kg" },
            { name: "Sebze & Izgara Baharı", price: "560", unit: "TL/kg" },
            { name: "Asya Wok Baharı", price: "620", unit: "TL/kg" },
            { name: "Pul Biber (Urfa/İsot)", price: "490", unit: "TL/kg" },
            { name: "Karabiber (Tane, Siyah)", price: "1190", unit: "TL/kg" },
            { name: "Karabiber (Toz, Siyah)", price: "1090", unit: "TL/kg" },
            { name: "Kimyon", price: "640", unit: "TL/kg" },
            { name: "Dağ Kekiği", price: "540", unit: "TL/kg" },
            { name: "Sumak", price: "590", unit: "TL/kg" },
            { name: "Toz Kırmızı Biber (Tatlı)", price: "470", unit: "TL/kg" },
            { name: "Toz Kırmızı Biber (Acı)", price: "470", unit: "TL/kg" },
            { name: "Sarımsak Tozu", price: "790", unit: "TL/kg" },
            { name: "Soğan Tozu", price: "640", unit: "TL/kg" },
            { name: "Közlenmiş Biber Tozu", price: "940", unit: "TL/kg" },
            { name: "Tane Hardal (Sarı)", price: "640", unit: "TL/kg" },
            { name: "Tane Hardal (Siyah)", price: "690", unit: "TL/kg" },
            { name: "Zerdeçal", price: "890", unit: "TL/kg" },
            { name: "Zencefil Tozu", price: "990", unit: "TL/kg" },
            { name: "Tarçın (Toz)", price: "790", unit: "TL/kg" },
            { name: "Yenibahar (Toz)", price: "1140", unit: "TL/kg" },
            { name: "Karanfil (Tane)", price: "1340", unit: "TL/kg" },
            { name: "Defne Yaprağı (Bütün)", price: "540", unit: "TL/kg" },
            { name: "Nane (Kuru)", price: "510", unit: "TL/kg" },
            { name: "Rezene Tohumu", price: "740", unit: "TL/kg" },
            { name: "Çörek Otu", price: "590", unit: "TL/kg" },
            { name: "Susam (Kavrulmuş)", price: "470", unit: "TL/kg" },
            { name: "Keten Tohumu", price: "510", unit: "TL/kg" },
            { name: "Kekik (Toz, Izgara Tipi)", price: "540", unit: "TL/kg" },
            { name: "Biberiye (Kuru)", price: "590", unit: "TL/kg" },
            { name: "Fesleğen (Kuru)", price: "640", unit: "TL/kg" },
            { name: "Dereotu (Kuru)", price: "540", unit: "TL/kg" },
            { name: "Maydanoz (Kuru)", price: "490", unit: "TL/kg" },
            { name: "Himalaya Tuzu (İri Tane)", price: "150", unit: "TL/kg" },
            { name: "Himalaya Tuzu (İnce)", price: "170", unit: "TL/kg" },
            { name: "Deniz Tuzu (İri Tane)", price: "90", unit: "TL/kg" },
            { name: "Kaya Tuzu (İri Tane)", price: "70", unit: "TL/kg" },
            { name: "Füme Tuz (Meşe Tütsülü)", price: "790", unit: "TL/kg" },
            { name: "Sarımsaklı Tuz", price: "440", unit: "TL/kg" },
            { name: "Tuz Öğütücü (Boş, Seramik)", price: "170", unit: "TL/tane" },
            { name: "Karabiber Öğütücü (Boş, Seramik)", price: "170", unit: "TL/tane" },
            { name: "Tuz-Karabiber Öğütücü Set (2'li)", price: "310", unit: "TL/set" },
            { name: "Baharat Saklama Kavanoz Seti (6'lı)", price: "450", unit: "TL/set" },
            { name: "Elma Sirkesi (Ev Yapımı)", price: "110", unit: "TL/L" },
            { name: "Üzüm Sirkesi (Ev Yapımı)", price: "100", unit: "TL/L" },
            { name: "Alıç Sirkesi (Doğal Fermente)", price: "170", unit: "TL/L" },
            { name: "Domates Salçası (Ev Yapımı)", price: "170", unit: "TL/kg" },
            { name: "Biber Salçası (Ev Yapımı, Acı)", price: "190", unit: "TL/kg" },
            { name: "Atom Biberi (Kuru Dökme Acı)", price: "590", unit: "TL/kg" },
            { name: "Taze Çekim Türk Kahvesi", price: "470", unit: "TL/kg" },
            { name: "Otomatik Tuz-Karabiber Set (Şarjlı)", price: "570", unit: "TL/set" }
        ]
    },
    // ==========================================
    // 2. İTHAL BUTİK BARBEKÜ SOSLARI – METRO (12)
    // ==========================================
    {
        id: "sos",
        icon: "fa-fire",
        title: "İthal Butik Barbekü Sosları – Metro",
        shortDesc: "Metro Toptan'dan özenle seçilmiş dünyaca ünlü ithal barbekü ve acı soslar. 12 çeşit.",
        color: "#BF360C",
        products: [
            { name: "Sweet Baby Ray's Original BBQ", price: "170", unit: "TL/şişe" },
            { name: "Sweet Baby Ray's Honey BBQ", price: "175", unit: "TL/şişe" },
            { name: "Sweet Baby Ray's Hickory & Brown Sugar", price: "175", unit: "TL/şişe" },
            { name: "Jack Daniel's Original BBQ", price: "205", unit: "TL/şişe" },
            { name: "Jack Daniel's Honey BBQ", price: "205", unit: "TL/şişe" },
            { name: "Jack Daniel's Spicy BBQ", price: "210", unit: "TL/şişe" },
            { name: "HP Sauce (Original)", price: "125", unit: "TL/şişe" },
            { name: "HP Sauce (BBQ)", price: "130", unit: "TL/şişe" },
            { name: "Sriracha Hot Chili Sos", price: "120", unit: "TL/şişe" },
            { name: "Tabasco Original Kırmızı Acı", price: "140", unit: "TL/şişe" },
            { name: "Tabasco Habanero Acı", price: "155", unit: "TL/şişe" },
            { name: "Tabasco Chipotle Acı", price: "155", unit: "TL/şişe" }
        ]
    },
    // ==========================================
    // 3. MANGAL, MALZEMELERİ & TERMAL SERVİS (66)
    // ==========================================
    {
        id: "mangal",
        icon: "fa-fire-burner",
        title: "Mangal, Malzemeleri & Termal Servis",
        shortDesc: "Mangal, kömür, ekipman, sarf malzemesi, döküm, termal servis, kıyma makinesi, bıçak setleri, bileme ürünleri, baskül ve et makası. 66 çeşit.",
        color: "#2E7D32",
        products: [
            { name: "Meşe Kömürü (10 kg)", price: "270", unit: "TL/paket" },
            { name: "Hindistan Cevizi Kömürü (5 kg)", price: "390", unit: "TL/paket" },
            { name: "Doğal Çıra (1 kg)", price: "60", unit: "TL/paket" },
            { name: "Tutuşturucu Jel (500 ml)", price: "75", unit: "TL/tane" },
            { name: "Odun Yünü", price: "40", unit: "TL/paket" },
            { name: "Hazır Mangal Torbası", price: "95", unit: "TL/tane" },
            { name: "Küçük Seyyar Mangal", price: "690", unit: "TL/tane" },
            { name: "Orta Boy Mangal", price: "1190", unit: "TL/tane" },
            { name: "Büyük Profesyonel Mangal", price: "2390", unit: "TL/tane" },
            { name: "Masaüstü Mini Mangal", price: "490", unit: "TL/tane" },
            { name: "Izgara Teli (Standart)", price: "160", unit: "TL/tane" },
            { name: "Izgara Teli (Döküm)", price: "440", unit: "TL/tane" },
            { name: "Balık Sepeti (Çift Taraflı)", price: "250", unit: "TL/tane" },
            { name: "Şiş Seti (6'lı Paslanmaz)", price: "190", unit: "TL/set" },
            { name: "Maşa (Uzun Saplı)", price: "110", unit: "TL/tane" },
            { name: "Mangal Çatalı", price: "100", unit: "TL/tane" },
            { name: "Maşa-Çatal Seti (2'li)", price: "160", unit: "TL/set" },
            { name: "Mangal Fırçası", price: "90", unit: "TL/tane" },
            { name: "Yağlama Fırçası (Silikon)", price: "60", unit: "TL/tane" },
            { name: "Marine Enjektörü", price: "75", unit: "TL/tane" },
            { name: "Yağlı Kağıt (10 mt)", price: "45", unit: "TL/tane" },
            { name: "Alüminyum Folyo (10 mt)", price: "55", unit: "TL/tane" },
            { name: "Streç Film", price: "40", unit: "TL/tane" },
            { name: "Pişirme Poşeti (5'li)", price: "55", unit: "TL/paket" },
            { name: "Marinasyon Poşeti (10'lu)", price: "65", unit: "TL/paket" },
            { name: "Isıya Dayanıklı Eldiven", price: "150", unit: "TL/çift" },
            { name: "Kül Kovası (Galvaniz)", price: "170", unit: "TL/tane" },
            { name: "Portatif Rüzgarlık", price: "230", unit: "TL/tane" },
            { name: "Ateş Körüğü", price: "130", unit: "TL/tane" },
            { name: "Mangal Termometresi", price: "190", unit: "TL/tane" },
            { name: "Mangal Temizleme Spreyi", price: "80", unit: "TL/tane" },
            { name: "Izgara Temizleme Taşı", price: "55", unit: "TL/tane" },
            { name: "Tel Temizleme Fırçası", price: "120", unit: "TL/tane" },
            { name: "Islak Mendil (Mangal Paket)", price: "40", unit: "TL/paket" },
            { name: "Döküm Tava (Küçük)", price: "410", unit: "TL/tane" },
            { name: "Sac Tava", price: "350", unit: "TL/tane" },
            { name: "Döküm Servis Tavası (Mangal)", price: "330", unit: "TL/tane" },
            { name: "Termal Servis Tepsisi (Kapaklı)", price: "390", unit: "TL/tane" },
            { name: "Termal Mangal Saklama Kabı", price: "470", unit: "TL/tane" },
            { name: "Çöp Torbası (Ağır İş, 10'lu)", price: "65", unit: "TL/paket" },
            { name: "Tane Karabiber (Dolum)", price: "110", unit: "TL/100gr" },
            { name: "Mangal Termosu (Et Sıcak Tutucu)", price: "530", unit: "TL/tane" },
            { name: "Termal Taşıma Çantası", price: "270", unit: "TL/tane" },
            { name: "Kömür Taşıma Kovası", price: "140", unit: "TL/tane" },
            { name: "Mangal Önlüğü (Deri)", price: "340", unit: "TL/tane" },
            { name: "Mangal Şapkası (B&M Logolu)", price: "170", unit: "TL/tane" },
            { name: "Katlanır Mangal Masası", price: "640", unit: "TL/tane" },
            { name: "Çakmak (Uzun Saplı, Mangal)", price: "55", unit: "TL/tane" },
            { name: "Kül Fırçası (Uzun Saplı)", price: "85", unit: "TL/tane" },
            { name: "Marine Kabı Seti (3'lü)", price: "270", unit: "TL/set" },
            { name: "Et Dinlendirme Filesi", price: "75", unit: "TL/tane" },
            { name: "Kıyma Çekme Makinesi (Manuel, 8 No)", price: "840", unit: "TL/tane" },
            { name: "Kıyma Çekme Makinesi (Manuel, 10 No)", price: "1190", unit: "TL/tane" },
            { name: "Kıyma Makinesi Bıçağı (Yedek, 8 No)", price: "110", unit: "TL/tane" },
            { name: "Kıyma Makinesi Bıçağı (Yedek, 10 No)", price: "140", unit: "TL/tane" },
            { name: "Kıyma Makinesi Aynası (Delikli Disk)", price: "75", unit: "TL/tane" },
            { name: "Mangal Bıçağı (Profesyonel, 25cm)", price: "340", unit: "TL/tane" },
            { name: "Et Bıçağı (Kasap Tipi, 20cm)", price: "270", unit: "TL/tane" },
            { name: "Satır (El Yapımı, 18cm)", price: "410", unit: "TL/tane" },
            { name: "Bıçak Seti (3'lü, Mangal Tipi)", price: "840", unit: "TL/set" },
            { name: "Bıçak Seti (5'li, Profesyonel)", price: "1390", unit: "TL/set" },
            { name: "Kemik Ayırma Bıçağı (15cm)", price: "210", unit: "TL/tane" },
            { name: "Bıçak Bileme Taşı (Çift Taraflı)", price: "270", unit: "TL/tane" },
            { name: "Bıçak Bileme Çubuğu (Masat, 25cm)", price: "170", unit: "TL/tane" },
            { name: "Bıçak Bileme Makinesi (Elektrikli)", price: "640", unit: "TL/tane" },
            { name: "Bıçak Bileme Taşı Seti (Profesyonel)", price: "570", unit: "TL/set" },
            { name: "Dijital Mutfak Baskülü (10 kg)", price: "270", unit: "TL/tane" },
            { name: "Ağır İş Mutfak Makası (Paslanmaz)", price: "150", unit: "TL/tane" },
            { name: "Tavuk Makası (Profesyonel)", price: "190", unit: "TL/tane" }
        ]
    },
    // ==========================================
    // 4. BAHÇE DEKORASYONU & AYDINLATMA (49)
    // ==========================================
    {
        id: "dekorasyon",
        icon: "fa-lightbulb",
        title: "Bahçe Dekorasyonu & Aydınlatma",
        shortDesc: "Solar ve elektrikli aydınlatma, saksı, rüzgar çanı, su öğeleri, bahçe aletleri, paspas ve tabela. 49 çeşit.",
        color: "#FF8F00",
        products: [
            { name: "Solar Bahçe Direği", price: "170", unit: "TL/tane" },
            { name: "Solar Duvar Aplikasyonu", price: "210", unit: "TL/tane" },
            { name: "Solar Çalı Aydınlatma", price: "130", unit: "TL/tane" },
            { name: "Solar LED Şerit", price: "250", unit: "TL/tane" },
            { name: "Solar Fener", price: "180", unit: "TL/tane" },
            { name: "Solar Güvenlik Işığı", price: "280", unit: "TL/tane" },
            { name: "LED Bahçe Spotu", price: "340", unit: "TL/tane" },
            { name: "Sarkıt Avize (Dış Mekan)", price: "640", unit: "TL/tane" },
            { name: "Duvar Lambiri", price: "410", unit: "TL/tane" },
            { name: "Zemin Aydınlatma", price: "470", unit: "TL/tane" },
            { name: "Havuz Başı Aydınlatma", price: "690", unit: "TL/tane" },
            { name: "Ağaç Altı Uplight", price: "540", unit: "TL/tane" },
            { name: "LED Mum (Pilli)", price: "90", unit: "TL/tane" },
            { name: "LED Şerit (RGB)", price: "270", unit: "TL/tane" },
            { name: "Çalı Ağı Işık", price: "210", unit: "TL/tane" },
            { name: "Yıldız Işık Perdesi", price: "250", unit: "TL/tane" },
            { name: "Hasır Top Lamba", price: "300", unit: "TL/tane" },
            { name: "Kağıt Fener", price: "70", unit: "TL/tane" },
            { name: "Mason Jar Işık", price: "110", unit: "TL/tane" },
            { name: "Portatif Kamp Lambası", price: "210", unit: "TL/tane" },
            { name: "Mangal Masası LED", price: "160", unit: "TL/tane" },
            { name: "Ateş Başı Fener", price: "250", unit: "TL/tane" },
            { name: "Gaz Lambası", price: "340", unit: "TL/tane" },
            { name: "Terracotta Saksı (Büyük)", price: "110", unit: "TL/tane" },
            { name: "Beton Saksı (Modern)", price: "210", unit: "TL/tane" },
            { name: "Ahşap Çiçeklik", price: "280", unit: "TL/tane" },
            { name: "Asma Saksı", price: "90", unit: "TL/tane" },
            { name: "Dikey Bahçe Paneli", price: "410", unit: "TL/tane" },
            { name: "Balkon Çiçekliği", price: "250", unit: "TL/tane" },
            { name: "Bambu Rüzgar Çanı", price: "170", unit: "TL/tane" },
            { name: "Metal Rüzgar Çanı", price: "220", unit: "TL/tane" },
            { name: "Seramik Rüzgar Çanı", price: "190", unit: "TL/tane" },
            { name: "Deniz Kabuğu Rüzgar Çanı", price: "180", unit: "TL/tane" },
            { name: "Masaüstü Şelale", price: "480", unit: "TL/tane" },
            { name: "Güneş Enerjili Fıskiye", price: "280", unit: "TL/tane" },
            { name: "Kuş Çeşmesi", price: "340", unit: "TL/tane" },
            { name: "Bambu Su Değirmeni", price: "540", unit: "TL/tane" },
            { name: "El Malası", price: "80", unit: "TL/tane" },
            { name: "Çapa", price: "100", unit: "TL/tane" },
            { name: "Tırmık", price: "90", unit: "TL/tane" },
            { name: "Budama Makası", price: "170", unit: "TL/tane" },
            { name: "Bahçe Eldiveni", price: "60", unit: "TL/çift" },
            { name: "Sulama Kabı", price: "120", unit: "TL/tane" },
            { name: "Bahçe Hortumu (15 mt)", price: "210", unit: "TL/tane" },
            { name: "Fıskiye (Döner Başlıklı)", price: "130", unit: "TL/tane" },
            { name: "Hoş Geldin Paspası", price: "170", unit: "TL/tane" },
            { name: "Komik Bahçe Tabelası", price: "100", unit: "TL/tane" },
            { name: "Ev Numarası (Işıklı)", price: "140", unit: "TL/tane" },
            { name: "Posta Kutusu (Metal)", price: "340", unit: "TL/tane" }
        ]
    },
    // ==========================================
    // 5. BAHÇE SÜS EŞYASI, ZÜCCACİYE, MOBİLYA & NİŞ KOLEKSİYON (53)
    // ==========================================
    {
        id: "sus-esya",
        icon: "fa-gem",
        title: "Bahçe Süs Eşyası, Züccaciye, Mobilya & Niş Koleksiyon",
        shortDesc: "Heykel, mumluk, duvar süsü, mangal sofrası, bahçe oyunları, butik mobilya, niş ürünler ve büyük mobilya. 53 çeşit.",
        color: "#4A148C",
        products: [
            { name: "Taş Kaplumbağa (Büyük)", price: "240", unit: "TL/tane" },
            { name: "Beton Cüce (El Boyaması)", price: "270", unit: "TL/tane" },
            { name: "Melek Figürü (Taş)", price: "310", unit: "TL/tane" },
            { name: "Kuş Banyosu (Mermer)", price: "470", unit: "TL/tane" },
            { name: "Buda Heykeli (Beton)", price: "370", unit: "TL/tane" },
            { name: "Baykuş Figürü (Seramik)", price: "230", unit: "TL/tane" },
            { name: "Kurbağa Heykeli (Taş)", price: "190", unit: "TL/tane" },
            { name: "Metal Fener (Büyük, Antik)", price: "410", unit: "TL/tane" },
            { name: "Metal Fener (Küçük, Antik)", price: "270", unit: "TL/tane" },
            { name: "Cam Mumluk (Renkli)", price: "110", unit: "TL/tane" },
            { name: "Citronella Mumu (Büyük)", price: "90", unit: "TL/tane" },
            { name: "Meşale (Bahçe, Yağlı)", price: "180", unit: "TL/tane" },
            { name: "Yağ Lambası (Dekoratif)", price: "150", unit: "TL/tane" },
            { name: "Metal Duvar Panosu (Büyük)", price: "310", unit: "TL/tane" },
            { name: "Ahşap Duvar Yazısı (El Yapımı)", price: "270", unit: "TL/tane" },
            { name: "Seramik Duvar Tabağı", price: "220", unit: "TL/tane" },
            { name: "Çiçek Çelengi (Kurutulmuş)", price: "170", unit: "TL/tane" },
            { name: "Makrome Duvar Süsü", price: "240", unit: "TL/tane" },
            { name: "Kuş Evi (Ahşap)", price: "330", unit: "TL/tane" },
            { name: "Ahşap Servis Tahtası (Zeytin)", price: "230", unit: "TL/tane" },
            { name: "Meze Tabağı Seti (6'lı)", price: "310", unit: "TL/set" },
            { name: "Baharatlık Seti (Bambu)", price: "270", unit: "TL/set" },
            { name: "Kupa (B&M Logolu)", price: "110", unit: "TL/tane" },
            { name: "Salsa Kasesi (El Yapımı)", price: "150", unit: "TL/tane" },
            { name: "Masa Tenisi Seti (Portatif)", price: "570", unit: "TL/set" },
            { name: "Dart (Profesyonel)", price: "370", unit: "TL/tane" },
            { name: "Dev Jenga (Bahçe Tipi)", price: "510", unit: "TL/tane" },
            { name: "Fasulye Torbası Oyunu", price: "310", unit: "TL/tane" },
            { name: "Badminton Seti (4 Kişilik)", price: "440", unit: "TL/set" },
            { name: "Dev Satranç Takımı (Bahçe)", price: "1790", unit: "TL/set" },
            { name: "Katlanır Ahşap Sandalye (Akasya)", price: "610", unit: "TL/tane" },
            { name: "Kamp Koltuğu (Taşınabilir)", price: "510", unit: "TL/tane" },
            { name: "Ahşap Piknik Masası (6 Kişilik)", price: "1340", unit: "TL/tane" },
            { name: "Bambu Sehpa (Doğal)", price: "740", unit: "TL/tane" },
            { name: "Hamak (Renkli, Çift Kişilik)", price: "670", unit: "TL/tane" },
            { name: "Salıncak (Ahşap, Tek Kişilik)", price: "1190", unit: "TL/tane" },
            { name: "Portatif Kamp Masası", price: "590", unit: "TL/tane" },
            { name: "Bahçe Şemsiyesi (Klasik, Kırmızı)", price: "890", unit: "TL/tane" },
            { name: "Ateş Başı Battaniyesi (Yün)", price: "570", unit: "TL/tane" },
            { name: "Esprili Mangal Önlüğü", price: "250", unit: "TL/tane" },
            { name: "Portatif Bluetooth Hoparlör", price: "670", unit: "TL/tane" },
            { name: "B&M Logolu Termos (Çelik)", price: "330", unit: "TL/tane" },
            { name: "Kilim Desenli Halı (Dış Mekan)", price: "740", unit: "TL/tane" },
            { name: "Bahçe Oturma Grubu (Rattan, 4 Parça)", price: "14490", unit: "TL/set" },
            { name: "Ahşap Bahçe Masası (6 Kişilik)", price: "4190", unit: "TL/tane" },
            { name: "Ahşap Bahçe Sandalyesi (Akasya)", price: "1790", unit: "TL/tane" },
            { name: "Bambu Salıncak (Tek Kişilik)", price: "3190", unit: "TL/tane" },
            { name: "Rattan Salıncak (Çift Kişilik)", price: "4790", unit: "TL/tane" },
            { name: "Metal Bahçe Sandalyesi (4'lü)", price: "3590", unit: "TL/set" },
            { name: "Ahşap Piknik Masası (4 Kişilik)", price: "1590", unit: "TL/tane" },
            { name: "Bahçe Şezlongu (Ahşap)", price: "2790", unit: "TL/tane" },
            { name: "Su Geçirmez Minder (4'lü Set)", price: "310", unit: "TL/set" },
            { name: "Bahçe Salıncağı (Metal, 3 Kişilik)", price: "6490", unit: "TL/tane" }
        ]
    },
    // ==========================================
    // 6. AÇIK HAVA KONFORU (12)
    // ==========================================
    {
        id: "konfor",
        icon: "fa-temperature-high",
        title: "Açık Hava Konforu",
        shortDesc: "Isıtma, soğutma, gölgelendirme ve tamamlayıcı ürünler. 12 çeşit.",
        color: "#1565C0",
        products: [
            { name: "Gazlı Mantar Isıtıcı (Paslanmaz)", price: "6190", unit: "TL/tane" },
            { name: "Elektrikli Infrared Isıtıcı (Ayaklı)", price: "3590", unit: "TL/tane" },
            { name: "Ateş Çukuru (Dekoratif, Çelik)", price: "1790", unit: "TL/tane" },
            { name: "Masaüstü Gazlı Mini Isıtıcı", price: "1290", unit: "TL/tane" },
            { name: "Misting Sis Sistemi (Set)", price: "1190", unit: "TL/set" },
            { name: "Portatif Evaporatif Soğutucu", price: "6190", unit: "TL/tane" },
            { name: "Ayaklı Endüstriyel Pervane", price: "2890", unit: "TL/tane" },
            { name: "Konsol / Yandan Direkli Şemsiye", price: "4990", unit: "TL/tane" },
            { name: "Klasik Bahçe Şemsiyesi (Alüminyum)", price: "1290", unit: "TL/tane" },
            { name: "Yelken Gölgelik (Shade Sail)", price: "890", unit: "TL/tane" },
            { name: "Sivrisinek Kovucu Elektronik Cihaz", price: "440", unit: "TL/tane" },
            { name: "Manyetik Sineklik Kapısı", price: "570", unit: "TL/tane" }
        ]
    },
    // ==========================================
    // 7. SUNİ ÇİM, ÇİT & BRANDA FİLE (10)
    // ==========================================
    {
        id: "cim",
        icon: "fa-leaf",
        title: "Suni Çim, Çit & Branda File",
        shortDesc: "Suni çim (m²), suni çit (mt) ve %95 gölgelik branda file. 10 çeşit.",
        color: "#558B2F",
        products: [
            { name: "Suni Çim (20mm, Ekonomik)", price: "170", unit: "TL/m²" },
            { name: "Suni Çim (35mm, Premium)", price: "280", unit: "TL/m²" },
            { name: "Suni Çim (40mm, Profesyonel)", price: "410", unit: "TL/m²" },
            { name: "Suni Çim Çit (1x3m, Ekonomik)", price: "130", unit: "TL/mt" },
            { name: "Suni Çim Çit (1x3m, Premium)", price: "190", unit: "TL/mt" },
            { name: "Suni Çit (Bambu Desen, 1x2m)", price: "160", unit: "TL/mt" },
            { name: "Branda Gölgelik File (%95, 2x3m)", price: "240", unit: "TL/tane" },
            { name: "Branda Gölgelik File (%95, 3x4m)", price: "410", unit: "TL/tane" },
            { name: "Branda Gölgelik File (%95, 4x6m)", price: "710", unit: "TL/tane" },
            { name: "Branda File (Metreyle Kesim)", price: "110", unit: "TL/m²" }
        ]
    }
];